### ISSUE TITLE
Cancelling mission kills server!

### ISSUE THREAD

**Issue by nachivpn** [molr/molr-remote#1]
This issue should disappear when the supervisor is spawned in a separate JVM. As of now (first commit), it's just EventualExit doing it's job!

**Comment by nachivpn** [comment]
after 100bb530c069156359bf734c591c003957c3e215, the server itself does not die, but the instead the mole supervisor does. Will this do? Or should the mole be spawned in a separate JVM altogether? System.exit seems to be to only way to **guarantee** cancellation of missions? EventualExit is a naive attempt at ensuring that an acknowledgement is sent back before a the JVM running the mission dies

**Comment by nachivpn** [comment]
It might be a better solution to setup a shutdown hook to send an acknowledgement, as the mole-supervisor would not have to wait an arbitrary amount of time before exit

**Comment by yassine-kr** [comment]
Missions are now executed on separate JVM. So cancelling a mission does not kill a supervisor server, as it is just a killing of the JVM.

Concerning the issue of sending back an Acknowledgement to client of an effective mission cancelling; thanks to new structure of controlling a mission, this problem can be resolved using two ways:

- For each command sent to supervisor, a status is returned to client which tells him whether the command was accepted or not (not executed yet). This behavior is already implemented.
-  Adding a shutdown hook which sends an event just before the the JVM is killed, not implemented.

Should this issue be closed and report "Add a shutdown hook to send a terminating event" in a new issue?

**Comment by jcgarnier** [comment]
Hi Yassine,

Yes, I think you can close this issue and create a new one for the acknowledgement. Please name the issue "acknowledge the complete execution of the cancel command", and let's discuss in the office how to do it. I'm not sure I understand how you'll implement it with a shutdown hook.
