### ISSUE TITLE
The supervisor must be able to manage execution of many missions at the same time

### ISSUE THREAD

**Issue by yassine-kr** [molr/molr-remote#11]
The supervisor should be able to manage a set of mission execution sessions. Each mission is spawned in a new JVM, so the mission executions are a set of java processes which are running in parallel on the host where the supervisor is running.

**Comment by makemeunsee** [comment]
different supervisors will have different behaviors.
one supervisors could be able to run several missions in parallel, or not, or several mission types, or not.
