### ISSUE TITLE
Throw a meaningful exception when client tries to control (get result or cancel or step through) a non-existing mission

### ISSUE THREAD

**Issue by jcgarnier** [molr/molr-remote#2]

**Comment by yassine-kr** [comment]
This issue has two reasons: 
- Client program receives exceptions wrapped in classes extending `TryResponseFailure`. Exceptions are saved as objects referenced by `Throwable`. Deserealization of these objects lose real type of the exception.
-  The Api used by client to execute remotely missions returns `CompletableFuture`. Exceptions thrown in a completable future are instances of `CompletionException` wrapping the real exception.

Solutions:
- Sending class names of real exceptions to the client.
- Creating adapters for `CompletableFuture` to throw the real exceptions.
