### ISSUE TITLE
The supervisor must register itself in the MolR server, and unregister itself

### ISSUE THREAD

**Issue by jcgarnier** [molr/molr-remote#3]

**Comment by yassine-kr** [comment]
Registering supervisors in the MolR server is implemented. When the supervisor server is launched it sends a registration request to  MolR server. Managing unregistration requests is also implemented.

When should an unregistration request be sent?

I think that MolR server may have the possibility to unregister supervisors which become unreachable due to network problems.

**Comment by jcgarnier** [comment]
This gets complicated.
First, a supervisor should unregister itself when it stops.
But as you say, that's not enough. We have to make sure that the MolR server will not build a graveyard of dead supervisors. 
Maybe a small protocol in which the MolR server asks the supervisor for their status is required? we'd anyway need this protocol to be able to know the state of the supervisors (e.g. how many missions they are running, etc.)

**Comment by yassine-kr** [comment]
Yes, another use case is when MolR server should choose an available supervisor. It would send a request to a supervisor asking if it could handle a new mission.

**Comment by makemeunsee** [comment]
agreed to put in place a heartbeat mechanism.
eg, molr server dismisses a supervisor that does not reply to 5 heartbeats.
the strategy & times should be configurable.
later on, more metadata could be packed in the heartbeats.

**Comment by makemeunsee** [comment]
look into existing standard solutions, pick a reasonable one for our context (spring)

**Comment by yassine-kr** [comment]
After searching on the Internet of Java Spring technologies which can be used to implement a Heartbeat connection. I found that the STOMP protocol and its Spring implementation contains this functionality, but it has two drawbacks for our use case : 
- The STOMP protocol is used to implement a server which publishes streams of data to subscribed clients. The heartbeat is just a small functionality of the protocol, no need to use the whole protocol for this small functionality.
- The Spring implementation of STOMP does not work with the WebFlux stack https://github.com/spring-projects/spring-boot/issues/12932

So I think that the Heartbeat can simply be implemented using the WebFlux Websocket connection.
