### ISSUE TITLE
Exchanging data between system components

### ISSUE THREAD

**Issue by yassine-kr** [molr/molr-remote#9]
There are four components which exchange data between them:
- Client
- MolR server
- Supervisor
- JVM

Exchanged data is serialized into JSON using Jackson library. These are types of exchanged data:
 - Mission instantiation request
 - Response to an instantiation request
 - Event triggered by a mission execution
 - Getting events flux request
 - Mission control command
 - Response to a command

These types of data are represented by Java classes. These classes are referenced by the class-path of each component. Normal serialization (save only values of properties) of a POJO objects can be done without any problem; it is the case of mission instantiation requests and getting flux requests.
The other kind of data is represented using generic interfaces and/or contains generic references  as properties (like "Throwable" reference). Serializing these data should save the real types of objects in JSON text before sending it, so the receiver can obtain the real instance without losing part of data. This functionality is allowed by Jackson Library.

What is the best way of exchanging data:
 - Make all data represented by POJO classes.
 - Or use interfaces and send classes real names in JSON texts (current implementation).

**Comment by makemeunsee** [comment]
can you provide examples of the current implementation? and a sample from the POJO solution?
what are the pros/cons for each solution?

**Comment by yassine-kr** [comment]
Example of the current implementation: the client receive from the supervisor a flux of events; each event is an instance of a class implementing the interface "MoleExecutionEvent"; these are examples of the implemented events types :
```java
public class MissionStarted implements MoleExecutionEvent{
        private String missionClassName;
        private Object argument;
        private String moleClassName;
 //...
}

public class MissionFinished implements MoleExecutionEvent{
        private String missionClassName;
        private Object result;
        private String moleClassName;
//..
}

public class JVMInstantiated implements MoleExecutionEvent{
}

public class JVMDestroyed implements MoleExecutionEvent{
}

```

During the serialization of an event, the supervisor save in the JSON text the content of object properties and the name of the event concrete class. When the client receive the event, it does not know the event type until it reads the class name from JSON data, then it can create the good instance. This type deduction is also applied to object properties; for example the `MissionFinished` class contains a property of type `Object`, knowing the real type retrieved from JSON, the client can create the object appropriate property.

A POJO solution for sending events would be implemented using one concrete class representing all kind of events; and contains simple properties (primitive types, `String`  and containers of simple types) or concrete complex properties (not interfaces or abstract classes references), this would be an example of such class :

```java
public class Event {
         private String date;
         private String id;
         private EventType type;
         private List<String> messages;
//...
}
```

Interface solution:
Pros:
- Design using polymorphisme, so more maintainable. 

Cons:
- Sending more data: class names.

POJO solution:
Pros:
 - Easy integration with an other language.

**Comment by makemeunsee** [comment]
discussed, no strong incentive to move to POJO solution.
